apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v2er
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-v2er@sha256:92bf9513c0eec623b640d8d3a618322bbba2b635ee95d1f3e4a740a0c146e6ec
        name: my-nodejs
        resources: {}
status: {}
